-- public.categories definition

-- Drop table

-- DROP TABLE public.categories;
-- public."__EFMigrationsHistory" definition

-- Drop table

-- DROP TABLE public."__EFMigrationsHistory";

CREATE TABLE public."__EFMigrationsHistory" (
	"MigrationId" varchar(150) NOT NULL,
	"ProductVersion" varchar(32) NOT NULL,
	CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


CREATE TABLE public.categories (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NOT NULL,
	image_url text NULL,
	CONSTRAINT "PK_categories" PRIMARY KEY (id)
);
CREATE INDEX "IX_categories_name" ON public.categories USING btree (name);

COPY public.categories FROM '/tmp/init_data/categories.csv' DELIMITER ',' CSV HEADER;

-- public.makers definition

-- Drop table

-- DROP TABLE public.makers;

CREATE TABLE public.makers (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NOT NULL,
	image_url text NULL,
	CONSTRAINT "PK_makers" PRIMARY KEY (id)
);
CREATE INDEX "IX_makers_name" ON public.makers USING btree (name);

COPY public.makers FROM '/tmp/init_data/makers.csv' DELIMITER ',' CSV HEADER;


-- public.components definition

-- Drop table

-- DROP TABLE public.components;

CREATE TABLE public.components (
	component_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NOT NULL,
	model_name text NOT NULL,
	description text NOT NULL,
	category_id int4 NOT NULL,
	maker_id int4 NOT NULL,
	CONSTRAINT "PK_components" PRIMARY KEY (component_id)
);
CREATE INDEX "IX_components_category_id" ON public.components USING btree (category_id);
CREATE INDEX "IX_components_maker_id" ON public.components USING btree (maker_id);


-- public.components foreign keys

ALTER TABLE public.components ADD CONSTRAINT "FK_components_categories_category_id" FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE CASCADE;
ALTER TABLE public.components ADD CONSTRAINT "FK_components_makers_maker_id" FOREIGN KEY (maker_id) REFERENCES public.makers(id) ON DELETE CASCADE;

COPY public.components FROM '/tmp/init_data/components.csv' DELIMITER ',' CSV HEADER;

-- public.component_images definition

-- Drop table

-- DROP TABLE public.component_images;

CREATE TABLE public.component_images (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	component_id_fk int4 NOT NULL,
	image_url text NOT NULL,
	CONSTRAINT "PK_component_images" PRIMARY KEY (id)
);
CREATE INDEX "IX_component_images_component_id_fk" ON public.component_images USING btree (component_id_fk);


-- public.component_images foreign keys

ALTER TABLE public.component_images ADD CONSTRAINT "FK_component_images_components_component_id_fk" FOREIGN KEY (component_id_fk) REFERENCES public.components(component_id) ON DELETE CASCADE;

COPY public.component_images FROM '/tmp/init_data/component_images.csv' DELIMITER ',' CSV HEADER;


-- public.orders definition

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE public.orders (
	order_id varchar(17) NOT NULL,
	order_date date NOT NULL,
	CONSTRAINT "PK_orders" PRIMARY KEY (order_id)
);
CREATE INDEX "IX_orders_order_id" ON public.orders USING btree (order_id);


-- public.order_details definition

-- Drop table

-- DROP TABLE public.order_details;

CREATE TABLE public.order_details (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	order_id varchar(17) NOT NULL,
	quantity int4 NOT NULL,
	unit text NOT NULL,
	catalog_id varchar(6) NOT NULL,
	component_id int4 NOT NULL,
	CONSTRAINT "PK_order_details" PRIMARY KEY (id)
);
CREATE INDEX "IX_order_details_component_id" ON public.order_details USING btree (component_id);
CREATE INDEX "IX_order_details_order_id" ON public.order_details USING btree (order_id);


-- public.order_details foreign keys

ALTER TABLE public.order_details ADD CONSTRAINT "FK_order_details_components_component_id" FOREIGN KEY (component_id) REFERENCES public.components(component_id) ON DELETE CASCADE;
ALTER TABLE public.order_details ADD CONSTRAINT "FK_order_details_orders_order_id" FOREIGN KEY (order_id) REFERENCES public.orders(order_id) ON DELETE CASCADE;

-- マイグレーション記録追加
COPY public."__EFMigrationsHistory" FROM '/tmp/init_data/___EFMigrationsHistory.csv' DELIMITER ',' CSV HEADER;

-- シーケンス値修正
SELECT setval('components_component_id_seq', (SELECT MAX(component_id) FROM public.components));
SELECT setval('component_images_id_seq', (SELECT MAX(id) FROM public.component_images));
SELECT setval('makers_id_seq', (SELECT MAX(id) FROM public.makers));
SELECT setval('categories_id_seq', (SELECT MAX(id) FROM public.categories));
SELECT setval('order_details_id_seq', (SELECT MAX(id) FROM public.order_details));