-- public.categories definition

-- Drop table

-- DROP TABLE public.categories;

CREATE TABLE public.categories (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NOT NULL,
	image_url text NULL,
	CONSTRAINT "PK_categories" PRIMARY KEY (id)
);
CREATE INDEX "IX_categories_name" ON public.categories USING btree (name);

COPY public.categories FROM '/tmp/init_data/categories.csv' DELIMITER ',' CSV HEADER;

-- public.makers definition

-- Drop table

-- DROP TABLE public.makers;

CREATE TABLE public.makers (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	"name" text NOT NULL,
	image_url text NULL,
	CONSTRAINT "PK_makers" PRIMARY KEY (id)
);
CREATE INDEX "IX_makers_name" ON public.makers USING btree (name);

COPY public.makers FROM '/tmp/init_data/makers.csv' DELIMITER ',' CSV HEADER;